### ISSUE TITLE
childish cmd spammer

### ISSUE THREAD

**Issue by absstract** [ferderplays/HeadHunter#2]

**Comment by ferderplays** [comment]
i will be rewriting the shit, so it will be less CPU using

**Comment by absstract** [comment]
omg

**Comment by absstract** [comment]
its not the point your whole rat is shit

**Comment by ferderplays** [comment]
yea, i know it was sh!t(i am currently rewriting it). And that it was taking to much CPU, and ram, cause it was spamming cmd, but that's now fixed.

**Comment by absstract** [comment]
🤦 straight stupidity
